apiVersion: v1
kind: Job
metadata:
  name: mysql-init
spec: 
  template:
    spec:
      containers:
      - name: mysql-init
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: Secret
              key: password
        - name: MYSQL_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: Secret
              key: auth-password
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        command: ["/bin/sh", "-c"]
        args:
        - |
          mysql -h $MYSQL_HOST -P $MYSQL_PORT -u root -p$MYSQL_ROOT_PASSWORD << EOF
          CREATE DATABASE IF NOT EXISTS CurrencyConversionAPP;
          CREATE USER IF NOT EXISTS 'USER07' IDENTIFIED BY '$MYSQL_AUTH_PASSWORD';
          GRANT ALL PRIVILEGES ON CurrencyConversionAPP.* TO 'USER07';
          FLUSH PRIVILEGES;
          EOF
      restartPolicy: Never
